name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
#  dynamic:
#    name: Nx Cloud - Build on Dynamic Agents
#    runs-on: ubuntu-latest
#    env:
#      NX_CI_EXECUTION_ENV: dynamic
#    steps:
#      - uses: actions/checkout@v4
#        name: Checkout [Pull Request]
#        if: ${{ github.event_name == 'pull_request' }}
#        with:
#          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
#          ref: ${{ github.event.pull_request.head.sha }}
#          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
#          fetch-depth: 0
#
#      - uses: actions/checkout@v4
#        name: Checkout [Default Branch]
#        if: ${{ github.event_name != 'pull_request' }}
#        with:
#          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
#          fetch-depth: 0
#
#      # Set node/npm/yarn versions using volta
#      - uses: volta-cli/action@v4
#        with:
#          package-json-path: '${{ github.workspace }}/package.json'
#
#      - name: Use the package manager cache if available
#        uses: actions/setup-node@v3
#        with:
#          node-version: 20
#
#      - name: npm install
#        run: npm ci
#
#      - name: Check out the default branch
#        run: git branch --track main origin/main
#
#      - name: Start CI run
#        run: npx nx-cloud start-ci-run --distributes-on="./nx/workflows/dynamic-changesets.yaml"
#
#      - name: Run commands in parallel
#        run: |
#          pids=()
#
#          # list of commands to be run on agents
#          npx nx run-many -t build --parallel=2 --projects="large-*" &
#          pids+=($!)
#
#          # run all commands in parallel and bail if one of them fails
#          for pid in ${pids[*]}; do
#            if ! wait $pid; then
#              exit 1
#            fi
#          done
#
#          exit 0
  small:
    name: Nx Cloud - Build on Small Agents
    runs-on: ubuntu-latest
    env:
      NX_CI_EXECUTION_ENV: small
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      # Set node/npm/yarn versions using volta
      - uses: volta-cli/action@v4
        with:
          package-json-path: '${{ github.workspace }}/package.json'

      - name: Use the package manager cache if available
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: npm install
        run: npm ci

      - name: Check out the default branch
        run: git branch --track main origin/main

      - name: Start CI run
        run: npx nx-cloud start-ci-run --distributes-on="10 my-custom-small"

      - name: Run commands in parallel
        run: |
          pids=()

          # list of commands to be run on agents
          npx nx run-many -t build --parallel=2 --projects="small-*" &
          pids+=($!)

          # run all commands in parallel and bail if one of them fails
          for pid in ${pids[*]}; do
            if ! wait $pid; then
              exit 1
            fi
          done

          exit 0
  large:
    name: Nx Cloud - Build on Large Agents
    runs-on: ubuntu-latest
    env:
      NX_CI_EXECUTION_ENV: large
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      # Set node/npm/yarn versions using volta
      - uses: volta-cli/action@v4
        with:
          package-json-path: '${{ github.workspace }}/package.json'

      - name: Use the package manager cache if available
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: npm install
        run: npm ci

      - name: Check out the default branch
        run: git branch --track main origin/main

      - name: Start CI run
        run: npx nx-cloud start-ci-run --distributes-on="10 my-custom-large"

      - name: Run commands in parallel
        run: |
          pids=()

          # list of commands to be run on agents
          npx nx run-many -t build --parallel=2 --projects="large-*" &
          pids+=($!)

          # run all commands in parallel and bail if one of them fails
          for pid in ${pids[*]}; do
            if ! wait $pid; then
              exit 1
            fi
          done

          exit 0
